version: '3.8'
services:
  baseapi-app:
    image: maxiplux/django-jmeter
    restart: always
    platform: linux/amd64
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_HOST=5432

    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
  db:
    restart: on-failure
    image: postgres:13.2
    # volumes:
    #   - ~/volumes/jhipster/baseapi/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - '5432:5432'

volumes:
  cache:
    driver: local
